### PR TITLE
add languagecheck

### PR DESCRIPTION
**Pull request by JohannesBuchner**
Add languagecheck to the "Spell Checking and Linting" section.

<details>
  <summary>Short pitch</summary>

Describe why this change is made. Alternatively, refer to existing issues if
any. You could try to answer:

* Why do you find this tool awesome?

It finds common phrasing mistakes I make, drawing from several community maintained lists including the language editing team at A&A, and relatively simple but powerful analyses, such as a vs an and spelling mistakes (e.g., seperate).

* How do you use this tool in your workflow?

I analyse latex papers before submitting to journals with it.

* What advantages / disadvantages does it have compared to {another tool}?

The closest is probably TeXtidote. The differences are:

* TeXtidote analyses latex directly, languagecheck relies on the proven detex tool
* TeXtidote is aimed at spell-checking and grammar-checking general-purpose writing in several languages. languagecheck is aimed at scientific publishing in English journals (AE and BE), and focuses more on rephrasing ambiguous, misleading, overly long sentences (which may be okay grammar-wise).
* TeXtidote is written in Java, languagecheck is python.
* languagecheck includes several community-produced lists of common mistakes in scientific and other writing, such as from [here](https://www.aanda.org/images/stories/author/EnglishGuide-2021.pdf).
* languagecheck supports analysing papers on overleaf.

</details>

## Checklist

- [x] I have read and understood the [contribution guidelines](https://github.com/writing-resources/awesome-scientific-writing/blob/main/CONTRIBUTING.md).
- [x] If the entry is a software:
	- [x] it should be **maintained** (at least a commit / a release in the past 3 years),
	- [x] it is **open-source** with appropriate **license**
- [x] Table of contents has been updated (if a section is added / removed).
- [x] Contents have been sorted alphabetically.

### CODE REVIEW

**Review by maehr — CHANGES_REQUESTED** [review]
Hi @JohannesBuchner, thanks for your first contribution. I suggest you shorten the description to one sentence. Also, I advise you to add more documentation (CONTRIBUTING.md, SECURITY.md etc.) to your project. You can get some ideas from https://github.com/maehr/github-template.

**Review by ashwinvis — CHANGES_REQUESTED** [review]
Seconded @maehr on shortening the description. A "LICENSE" file appears to be missing from the `languagecheck` repository - which is important for its open-source status. The rest of the files that @maehr suggested are nice to have, but not mandatory, IMHO.

**Comment by ashwinvis** [comment]
Very nice project and interesting approach, btw!

**Comment by JohannesBuchner** [comment]
Sorry for the late update, added a LICENSE file and shortened the description to one sentence.

**Review by maehr — CHANGES_REQUESTED** [review]
Thanks for the update. There's an issue with the linter. You should use - instead of : as a separator for the description.
Best
M

**Comment by ashwinvis** [comment]
I took the liberty of fixing it in this PR and also updated the CI

**Pull request merged**
