### PR TITLE
Added few text editors

### PR DESCRIPTION
**Pull request by Nazeeefa**
Added:

- Notion
- MacDown

to the list of Word processors.

### CODE REVIEW

**Comment by ashwinvis** [comment]
Thanks. Overleaf would be a fine candidate for "Awesome Latex" list, so I would not include it here... As for the rest, I will wait until someone else can vote (:+1: or :-1:) on this PR.

**Comment by Nazeeefa** [comment]
It's already in the awesome-LaTeX list, the reason it was added here because it is used for scientific writing.

**Comment by maehr** [comment]
> Added:
> 
> * Notion
> * MacDown
> 
> to the list of Word processors.

Do you personally use these tools?

**Comment by maehr** [comment]
> Good Additions

Do you personally use these tools?

**Comment by Nazeeefa** [comment]
Yes. I personally use these tools. Is your next question going to be asking me to provide a screenshot of installation and how I use them?

Are you adding only those tools that are often used by you? I highly doubt that you have used all the tools mentioned in your list. 

There are etiquettes on how you should respond when someone, out of kindness, contributes to your repository. But, apparently, not everyone on Github follows them.

**Comment by ashwinvis** [comment]
We have a Code of Conduct, which I hope you read:

1. Demonstrating empathy and kindness toward other people
2. **Being respectful of differing opinions**, viewpoints, and experiences
3. Giving and gracefully accepting **constructive feedback**
4. Accepting responsibility and apologizing to those affected by our mistakes, and learning from the experience
5. Focusing on what is best not just for us as individuals, **but for the overall community**

It applies to maintainers and contributors both. Please understand, we are trying to work with you to provide constructive feedback. 

If you do not want to discuss this any further, let us know. However, that also means we might edit your contributions without notifying you.

**Comment by maehr** [comment]
> Yes. I personally use these tools. Is your next question going to be asking me to provide a screenshot of installation and how I use them?
> 
> Are you adding only those tools that are often used by you? I highly doubt that you have used all the tools mentioned in your list.
> 
> There are etiquettes on how you should respond when someone, out of kindness, contributes to your repository. But, apparently, not everyone on Github follows them.

Hi @Nazeeefa 

@ashwinvis and I have only added tools to the list that we actually use. (Cf. https://moritzmaehr.ch/macos-10-15-basic-configuration/ for example) But that is not the point. The idea behind awesome lists is not to gather all possible tools, but the best ones. Therefore I am honestly interested in how you use the suggested tools in your everyday research.
PS: We are also always grateful when people participate in public domain projects. We act on your suggestion and develop Contribution Guidelines.

**Comment by Nazeeefa** [comment]
> We have a Code of Conduct, which I hope you read:
> 
> 1. Demonstrating empathy and kindness toward other people
> 2. **Being respectful of differing opinions**, viewpoints, and experiences
> 3. Giving and gracefully accepting **constructive feedback**
> 4. Accepting responsibility and apologizing to those affected by our mistakes, and learning from the experience
> 5. Focusing on what is best not just for us as individuals, **but for the overall community**
> 
> It applies to maintainers and contributors both. Please understand, we are trying to work with you to provide constructive feedback.
> 
> If you do not want to discuss this any further, let us know. However, that also means we might edit your contributions without notifying you.

Yes, I did and it is very disrespectful to see that you have time to remind me of it but failed to follow it yourself.

There was no attempt from your side to provide constructive feedback. You seem to be unaware of what is in awesome-LaTeX list and, most importantly, you seem to be unaware of this repo's contribution guidelines; guidelines that I followed and made a polite attempt to contribute to your repository with an intention to help.

I know it's a small PR but I am very hurt by this interaction that I have not experienced on Github before.

You can edit my contributions without notifying me if that's your definition of handling PR with positive manners and feel free to add them to the list even though you have not personally used them.

**Comment by Nazeeefa** [comment]
> > Yes. I personally use these tools. Is your next question going to be asking me to provide a screenshot of installation and how I use them?
> > Are you adding only those tools that are often used by you? I highly doubt that you have used all the tools mentioned in your list.
> > There are etiquettes on how you should respond when someone, out of kindness, contributes to your repository. But, apparently, not everyone on Github follows them.
> 
> Hi @Nazeeefa
> 
> @ashwinvis and I have only added tools to the list that we actually use. (Cf. https://moritzmaehr.ch/macos-10-15-basic-configuration/ for example) But that is not the point. The idea behind awesome lists is not to gather all possible tools, but the best ones. Therefore I am honestly interested in how you use the suggested tools in your everyday research.
> PS: We are also always grateful when people participate in public domain projects. We act on your suggestion and develop Contribution Guidelines.

Hi @maehr Kindly make this clear in your contribution guidelines with this link that you mentioned https://moritzmaehr.ch/macos-10-15-basic-configuration/ even if if you think it's not important. I don't want anyone else to go through same negative experience as I just did.

I use Notion for project organisation including to-do list, and note-taking. I use MacDown for writing and sometimes for web content. As I wrote to your colleague, you can edit my contributions and feel free to add them to the list even though you have not personally used them.

I will be closing this pull request because, I found this interaction disrespectful and this is not a healthy space to engage.

**Comment by ashwinvis** [comment]
> Yes, I did and it is very disrespectful to see that you have time to remind me of it but failed to follow it yourself.

I brought it up as a reminder because the tone of the discussion was becoming aggressive - even for a simple one line question.

> There was no attempt from your side to provide constructive feedback. 

That was what @maehr was trying to do. And he did explain the reason for the question in the first place. Empathize, and stand in others shoes before throwing wild accusations. 

> I know it's a small PR but I am very hurt by this interaction that I have not experienced on Github before.
> I found this interaction disrespectful and this is not a healthy space to engage.

I do not know what to say. Maybe some other day you can tell us how we should have interacted with you.

> You can edit my contributions without notifying me if that's your definition of handling PR with positive manners and feel free to add them to the list even though you have not personally used them.

We will not add Notion as it is not open-source. I will leave Macdown as a reminder.

**Pull request closed without merging**
