### PR TITLE
Add BibTex and Zotero extensions for VSCode

### PR DESCRIPTION
**Pull request by jobindjohn**
Add to Word Processor

Add BibTex and Zotero extensions for VSCode

## Checklist

- [x] I have read and understood the [contribution guidelines](https://github.com/writing-resources/awesome-scientific-writing/blob/main/CONTRIBUTING.md).
- [x] If the entry is a software:
	- [x] it should be **maintained** (at least a commit / a release in the past 3 years),
	- [x] it is **open-source** with appropriate **license**
- [ ] Table of contents has been updated (if a section is added / removed).
- [x] Contents have been sorted alphabetically.

### CODE REVIEW

**Comment by maehr** [comment]
@jobindj Thank you very much for your contribution. Please set the links to the source (i.e. GitHub repo) and sort the entries alphabetically.
Cheers, moritz

**Review by maehr — CHANGES_REQUESTED** [review]
https://github.com/writing-resources/awesome-scientific-writing/pull/43#issuecomment-907588143

**Comment by ashwinvis** [comment]
Ping @jobindj, are you available to make the changes?

**Comment by maehr** [comment]
Stale PR

**Pull request closed without merging**
