### PR TITLE
removed markdeep due to not being awesome

### PR DESCRIPTION
**Pull request by maehr**
Remove Markdeep from the "Converters and Filters" section.

I've reviewed Markdeep and don't find it awesome. There is no active user and developer community.

- [ ] Table of contents has been updated (if needed).
- [ ] Contents have been sorted alphabetically.

### CODE REVIEW

**Comment by ashwinvis** [comment]
OK then in that case, you can remove the markdeep-thesis example as well.

**Comment by ashwinvis** [comment]
But you surely saw this: https://doersino.github.io/markdeep-thesis/demo.md.html did you not. This was why I added it in the first place.

**Comment by maehr** [comment]
> But you surely saw this: https://doersino.github.io/markdeep-thesis/demo.md.html did you not. This was why I added it in the first place.

It is indeed an impressive tech demo. I'm just missing an everyday use case.

**Comment by ashwinvis** [comment]
I agree it seems to be forgotten. We can remove it for now. Relevant thread for similar projects:

https://news.ycombinator.com/item?id=19488561

**Pull request merged**
